variable "ami_id" {}
variable "region" {}
variable "region_prefix" {}
variable "env" {}
#variable "ami_id" {}
#variable "apec1_ami_id" {}
variable "ec2_key_name" {}
variable "instance_type" {}
variable "vpc_cidr_block" {}
variable "project_name" {}
variable "private_app_subnet_az1_cidr" {}
variable "private_app_subnet_az2_cidr" {}
